---
- name: "TASK 1 - Add apt repository for PHP8"
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present
- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: latest 
- name: " TASK 4 - Add apache2 to autostart"
  ansible.builtin.systemd:
    name: apache2
    enabled: true
    state: started
- name: " TASK 5 - Install MariaDB packages"
  ansible.builtin.apt:
    name: "{{item}}"
    state: latest
  with_items:
    - software-properties-common
    - mariadb-server
    - mariadb-client
- name: " TASK 6 - Add mariadb to autostart"
  ansible.builtin.systemd:
    name: mysql
    enabled: true
- name: " TASK 7 - Install PHP8 packages"
  ansible.builtin.apt:
    name: "{{item}}"
    state: latest
  with_items:
    - php8.0
    - libapache2-mod-php8.0
    - php-gd
    - php-mail-mime
    - php8.0-mysqli
    - php-pear
    - php-db
    - php-mbstring
    - php-xml
    - php-curl

- name: " TASK 8 - Install Freeradius packages"
  ansible.builtin.apt:
    name: "{{item}}"
    state: latest
  with_items:
    - freeradius
    - freeradius-mysql
    - freeradius-utils
  tags: freeradius_install    

