---
- name: "Check if files for resource info exists"
  stat: 
    path: /home/kamil/{{ inventory_hostname }}.txt
  register: file_stat
- name: "Print msg if files exists"
  debug:
    msg: "File exists"
  when: file_stat.stat.exists
- name: "Print msg if files doesn't exists"  
  debug:
    msg: "Files doesn't exists. It will be created in next step"
  when: not file_stat.stat.exists
- name: "Creating files" 
  file:
    path: /home/kamil/{{ inventory_hostname }}.txt
    owner: kamil
    group: kamil
    mode: u=rw,g=rw,o=r
    state: touch
  when: not file_stat.stat.exists
- name: check primary info about devices
  routeros_command:
    commands: /system resource print     
  register: res_out
- name: "copy registered info to files "
  shell: echo "{{ res_out.stdout[0] }}" > /home/kamil/{{ inventory_hostname }}.txt
- name: check info about device interfaces
  routeros_command:
    commands: /interface/ethernet print
  register: int_out
- name: "Check if files for interfaces output exists"
  stat: 
    path: /home/kamil/{{ inventory_hostname }}-int.txt
  register: file_stat_int
- name: Print msg if files exists  
  debug:
    msg: "File exists"
  when: file_stat_int.stat.exists
- name: "Print msg if files exists"
  debug:
    msg: "File doesn't exists. It will be created in next step"
  when: not file_stat_int.stat.exists
- name: "create files"
  file:
    path: /home/kamil/{{ inventory_hostname }}-int.txt
    owner: kamil
    group: kamil
    mode: u=+rw,g=+rw,o=+r
    state: touch
  when: not file_stat_int.stat.exists
- name: "Check if files for ip address checks exists"
  stat: 
    path: /home/kamil/{{ inventory_hostname }}-ip.txt
  register: file_stat_ip
- name: "Print msg if files exists" 
  debug:
    msg: "Files exists"
  when: file_stat_ip.stat.exists
- name: Print msg if files doesn't exists  
  debug:
    msg: "File doesn't exists. It will be created in next step"
  when: not file_stat_ip.stat.exists
- name: "create files" 
  file:
    path: /home/kamil/{{ inventory_hostname }}-ip.txt
    owner: kamil
    group: kamil
    mode: u=+rw,g=+rw,o=+r
    state: touch
  when: not file_stat_ip.stat.exists
- name: "saving registered informations in file"
  shell: echo "{{ int_out.stdout[0]}}" > /home/kamil/{{ inventory_hostname }}-int.txt
- name: "check info about ip"
  routeros_command:
    commands: /ip address print
  register: ip_out
- name: "saving registered informations in file"
  shell: echo "{{ ip_out.stdout[0]}}" > /home/kamil/{{ inventory_hostname }}-ip.txt
